[versions]
androidGradlePlugin = "8.6.1"
kotlin = "1.9.22"

[plugins]
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
download = { id = "de.undercouch.download", version = "5.5.0" }
