# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, '15.1'
prepare_react_native_project!

ENV['RCT_NEW_ARCH_ENABLED'] = '0'

target 'tempCocolon' do
  use_frameworks! :linkage => :static
  $RNFirebaseAsStaticFramework = true

  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :fabric_enabled => false,
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'tempCocolonTests' do
    inherit! :complete
  end

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )

    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.1'
      end
    end

    # Archive on CI can fail with exit code 65 when CocoaPods-created resource bundles
    # inherit signing settings during a manual-signing archive. These bundle targets
    # do not need code signing.
    installer.pods_project.targets.each do |target|
      next unless target.respond_to?(:product_type)
      next unless target.product_type == "com.apple.product-type.bundle"

      target.build_configurations.each do |config|
        config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
        config.build_settings['CODE_SIGNING_REQUIRED'] = 'NO'
        config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ''
      end
    end
  end
end

